
export const DEFAULT_CAMERAS_CSV = ``;

export const DEFAULT_ACCESS_CSV = ``;

export const WAREHOUSE_LIST = [
    'GALPÃO G2',
    'GALPÃO G3',
    'GALPÃO G5',
    'GALPÃO SP',
    'GALPÃO PAVUNA',
    'GALPÃO 4 ELOS ES',
    'GALPÃO 4 ELOS RJ',
    'GALPÃO LSP',
    'GALPÃO MERITI',
    'TESTE'
];

export const RESPONSIBLE_WAREHOUSE_MAP: Record<string, string> = {
    "PRISCILA APARECIDA VIEIRA": "GALPÃO SP",
    "PAULO RICARDO SILVA": "GALPÃO SP",
    "RODRIGO SILVA GIMENES": "GALPÃO G5",
    "BRUNA CRUZ FARIA": "GALPÃO G2",
    "ALEX GUIDINI FERREIRA": "GALPÃO G5",
    "MOACIR ANDRADE NUNES": "GALPÃO G5",
    "TIAGO FERNANDES BASTOS": "GALPÃO 4 ELOS RJ",
    "JORGE LUIZ SILVA": "GALPÃO PAVUNA",
    "DIMAS SOUZA CASTELO": "GALPÃO G5",
    "MAURO BAPTISTA CERQUEIRA": "GALPÃO MERITI",
    "MARESSA MIRANDA SILVA": "TESTE",
    "ALLAN SOARES OLIVEIRA": "GALPÃO G5",
    "GABRIEL ANTONIO CARVALHO": "GALPÃO G2",
    "ANTONIO KATIEL BARCELOS": "GALPÃO G2",
    "HANANI SOUZA CELESTINO": "GALPÃO G5",
    "VICTOR DANTAS CASTRO": "GALPÃO 4 ELOS ES",
    "PAULO ROBERTO LADEIRA": "GALPÃO LSP",
    "JOSENIAS SANTOS NASCIMENTO": "GALPÃO SP",
    "ELIELSON COSTA PATROCINIO": "GALPÃO G5"
};
